export const formulario = document.querySelector(".f-form")
export const nombre = document.querySelector("#nombre")
export const email = document.querySelector("#email")
export const comentario = document.querySelector("#comentario")
export const mensaje = document.querySelector("#mensaje")
export const tema = document.querySelector("#tema")